Providers
santiagogabrielcastillo/planit pull request #5
Opened 2021-04-20 16:48 UTC by santiagogabrielcastillo

Adds providers controller, model and show method. Also, category model and service model, and associations

2021-04-20 17:33 UTC, jpbalarini requested changes
Looking great!
Let's change this:
- Category should be a record o the database since we need this to be dynamic. Admins can change this
- Let's model this: one provider could have many categories. A provider can sell breakfasts and brunches at the same time

2021-04-20 18:13 UTC, santiagogabrielcastillo commented
I've created the Category Model, the join table categories_providers and added the related associations to the models (I've decided for the "has_and_belongs_to_many" because there is no need to work with a join model)

2021-04-21 12:22 UTC, santiagogabrielcastillo commented
This is how providers/:id looks like:

![image](https://user-images.githubusercontent.com/71985198/115552686-f6808c80-a282-11eb-8d82-80c31b8d641d.png)

2021-04-21 13:58 UTC, jpbalarini approved these changes

2021-04-21 13:58 UTC, merged